### ISSUE TITLE
ExVersion is not returning #0 (A Realm Reborn)

### ISSUE THREAD

**Issue by zhyupe** [xivapi/xivapi.com#29]
https://xivapi.com/exversion contains Heavensward, Stormblood and Shadowbringers, but not A Realm Reborn. It should return all of them.

**Comment by vekien** [comment]
Sorry this is old, this should fix in the next content update: https://github.com/xivapi/xivapi.com/blob/master/src/Command/GameData/SaintCoinachRedisCommand.php#L29
