### ISSUE TITLE
Mount icons not working

### ISSUE THREAD

**Issue by Nachodlv** [xivapi/xivapi.com#31]
Example request: https://xivapi.com/character/730968?data=MIMO
The url from the icons are not returning the mount image but a black image.
```JSON
{"Icon":"https:\/\/img.finalfantasyxiv.com\/lds\/h\/y\/mh-Q9DC4CeD3dITnpD0a9nB8Tw.png","Name":"Legacy Chocobo"}
```
![image](https://user-images.githubusercontent.com/22358277/87555539-f6b48180-c68b-11ea-88b9-f3b005ef88fb.png)

**Comment by vekien** [comment]
Ah it's parsing the frame, I will fix this

**Comment by Nachodlv** [comment]
Yes, it's doing that.

![image](https://user-images.githubusercontent.com/22358277/87555944-73476000-c68c-11ea-8a9b-f84aea179832.png)

**Comment by vekien** [comment]
Fixed and pushed live.

**Comment by Nachodlv** [comment]
Working as expected. Thanks!
