### ISSUE TITLE
Character search by DC returns results from all DCs

### ISSUE THREAD

**Issue by Maia-Everett** [xivapi/xivapi.com#55]
https://xivapi.com/character/search?name=Vielle+Janlenoux&server=_dc_Chaos

Expected result: only one search result, from Omega (Chaos), is returned.

Actual result: three results are returned, two of them from DCs other than Chaos.

**Comment by hduyker** [comment]
Just looked into this.

Culprit is this line:

`                ucwords(strtolower($request->get('server'))),`

Link: https://github.com/xivapi/xivapi.com/blob/9e3fd0dff3ef8f24dff73af5bd8ae608ede77d99/src/Controller/LodestoneCharacterController.php#L51

What that does, is "proper-case" the server argument.

However, that's not working for datacenters.

Tried it out with the Lodestone search for the character "Ororo Oro" on the Spriggan server, Chaos datacenter.

Base search returns 111 results: https://eu.finalfantasyxiv.com/lodestone/character/?q=%22Ororo+Oro%22

This is good: `&worldname=Spriggan` 
This returns no results: `&worldname=spriggan`
This returns 111 results (like the API does now): `&worldname=_dc_chaos`
This returns the (correct number) of 5 results: `&worldname=_dc_Chaos`

So a check on server would be good.

So something like this:

```
$server = strtolower($request->get('server'));
$server = ( str_startswith($server, '_dc_') ? '_dc_' + ucwords(substr($server, 4)) : ucwords($server) );
```
... and then use that in the API call.

**Comment by Supamiu** [comment]
Hey, thanks for investigating this :) 

I just fixed a bug with this tolower done on dc filter but if you want to PR a change to make this non case-sensitive, please feel free to 👍

**Comment by Maia-Everett** [comment]
Seems fixed. Thank you!
