### ISSUE TITLE
Items data

### ISSUE THREAD

**Issue by ZatsuneSakurako** [xivapi/xivapi.com#61]
Hi,

Could it be possible to get the lodestone url of the items ?

For exemple https://xivapi.com/Item/36193 could give https://eu.finalfantasyxiv.com/lodestone/playguide/db/gathering/e0d72206e5e/ or at least the type / id of the lodestone.

**Comment by Supamiu** [comment]
No, this is not possible because we have no informations about how each item ID is converted to its lodestone key.
