### ISSUE TITLE
Fish catch times

### ISSUE THREAD

**Issue by ghost** [xivapi/xivapi.com#62]
Not sure if I'm just dumb or they really don't exist.. I've been trying to find data for fish catch times (for example Aapoak which is 12-16).
I've looked at both Item page and FishParameter. FishParameter only seemed to have "TimeRestriction: 1" which really is not that helpful.

If they do not exist, adding them would be very nice and helpful

**Comment by Supamiu** [comment]
Hi, XIVAPI is an API that provides easy access to the data that can be found in game files, and fish time/weather data cannot.

There's some solutions including the gubal API from Teamcraft to fetch fish data, but it's far from being easy and it changes a lot, considering everything is just found by players and filled into a crowd-sourced database by hand for each fish.
