### ISSUE TITLE
Orchestrion Roll searches returns no useful result

### ISSUE THREAD

**Issue by oott123** [xivapi/xivapi.com#69]
https://xivapi.com/search?indexes=Recipe&string=Orchestrion%20Roll can't return any results for orchestrion rolls.

PS. this issue is originally reported by a cafemaker user from https://github.com/thewakingsands/cafemaker/issues/7

**Comment by ArcaneDisgea** [comment]
I am super late but it looks like your PR may have fixed this so I am going to close it.
