### ISSUE TITLE
Google Analytics UA ID's cause server disconnects

### ISSUE THREAD

**Issue by ayyaruq** [xivapi/xivapi.com#76]
No idea what's actually changed, but any request with a GA UA ID set will eventually 499 in nginx and return a 524 to the user from CF. Looking at the DB, only 18 active users actually have the key set, where active means they have a `last_online` within the 1 year. Hard to get actual usage since redis isn't exactly persistent.

We could update to support GA4 but it's technically still beta despite throwing deprecations all up in it. Alternatively, and outside the scope of my skills, could fix existing GA3 support, or just remove it since barely anyone appears to use it.

**Comment by Supamiu** [comment]
Closed by https://github.com/xivapi/xivapi.com/commit/f75802d57e3e112c367900ea195d23773a390572
